force-app/main/default/objects/Payout__c/Payout__c.object-meta.xml
<CustomObject>
    <label>Payout</label>
    <pluralLabel>Payouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <nameField>
        <label>Payout Name</label>
        <type>Text</type>
    </nameField>
</CustomObject>

force-app/main/default/objects/Payout__c/fields/Is_Paid__c.field-meta.xml
<CustomField>
    <fullName>Is_Paid__c</fullName>
    <label>Is Paid</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <type>Lookup</type>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payouts</relationshipLabel>
    <relationshipName>Contact_Payouts</relationshipName>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Ownership_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Percentage__c</fullName>
    <label>Ownership Percentage</label>
    <type>Percent</type>
    <precision>3</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Payment_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction__c</fullName>
    <label>Payment Transaction</label>
    <type>Lookup</type>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Payout Payments</relationshipLabel>
    <relationshipName>Payout_Payments</relationshipName>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <type>LongTextArea</type>
    <length>32000</length>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <type>MasterDetail</type>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Payouts</relationshipLabel>
    <relationshipName>Payouts</relationshipName>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <type>Lookup</type>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Contact_Transactions</relationshipName>
</CustomField>

force-app/main/default/classes/selectors/PayoutSelector.cls
/* PayoutSelector.cls */
public inherited sharing class PayoutSelector extends fflib_SObjectSelector {


    
    /* 1. sObjectField list */
    private List<String> additionalSObjectFieldList = new List<String>{
        'Id',
        'Name',
        'Transaction__c',
        'Ownership_Percentage__c',
        'Amount__c',
        'Is_Paid__c',
        'Payment_Transaction__c',
        'Owner__c',
        'Remarks__c'
    };

    /* 2. Boilerplate code */
    public static PayoutSelector newInstance() {
        return (PayoutSelector) ITBA_Application_UTIL.selector.newInstance(
            Payout__c.SObjectType
        );
    }

    public Schema.SObjectType getSObjectType() {
        return Payout__c.SObjectType;
    }

    public fflib_QueryFactory getQueryFactory() {
        return new fflib_QueryFactory(getSObjectType());
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Payout__c.Id,
            Payout__c.Name,
            Payout__c.Transaction__c,
            Payout__c.Ownership_Percentage__c,
            Payout__c.Amount__c,
            Payout__c.Is_Paid__c,
            Payout__c.Payment_Transaction__c,
            Payout__c.Owner__c,
            Payout__c.Remarks__c
        };
    }

    public override Set<String> getRelatedFieldSet(){
        return new Set<String>{
            'Owner__c.Name'
        };
    }

    @TestVisible
    private List<Schema.SObjectField> getAdditionalSObjectFieldList() {
        return new List<Schema.SObjectField>{};
    }

    /* 3. Selector Methods */
    public List<Payout__c> selectByIds(Set<Id> idSet) {
        fflib_QueryFactory queryFactory = newQueryFactory(false, false, true ,true);
        queryFactory.setCondition('Id IN :idSet');
        return (List<Payout__c>) Database.query(queryFactory.toSOQL());
    }

    public List<Payout__c> selectByTransactionIds(Set<Id> idSet) {
        fflib_QueryFactory queryFactory = newQueryFactory(false, false, true ,true);
        queryFactory.setCondition('Transaction__c IN :idSet');
        return (List<Payout__c>) Database.query(queryFactory.toSOQL());
    }

}