force-app/main/default/objects/Payout__c/Payout__c.object-meta.xml
<CustomObject>
    <label>Payout</label>
    <pluralLabel>Payouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <nameField>
        <label>Payout Name</label>
        <type>Text</type>
    </nameField>
</CustomObject>

force-app/main/default/objects/Payout__c/fields/Is_Paid__c.field-meta.xml
<CustomField>
    <fullName>Is_Paid__c</fullName>
    <label>Is Paid</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <type>Lookup</type>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payouts</relationshipLabel>
    <relationshipName>Contact_Payouts</relationshipName>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Ownership_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Percentage__c</fullName>
    <label>Ownership Percentage</label>
    <type>Percent</type>
    <precision>3</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Payment_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction__c</fullName>
    <label>Payment Transaction</label>
    <type>Lookup</type>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Payout Payments</relationshipLabel>
    <relationshipName>Payout_Payments</relationshipName>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <type>LongTextArea</type>
    <length>32000</length>
</CustomField>

force-app/main/default/objects/Payout__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <type>MasterDetail</type>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Payouts</relationshipLabel>
    <relationshipName>Payouts</relationshipName>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <type>Lookup</type>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Contact_Transactions</relationshipName>
</CustomField>

force-app/main/default/classes/Payout__c/PayoutDomain.cls
public inherited sharing class PayoutDomain extends fflib_SObjectDomain implements IPayouts {
    public interface IPayouts {
        void validatePayouts();
        void validatePayouts(List<Payout__c> payouts);
    }

    private Map<Id, Payout__c> oldPayoutsById;

    public static IPayouts newInstance(List<Payout__c> records) {
        return (IPayouts) ITBA_Application_UTIL.domain.newInstance(records);
    }

    public static IPayouts newInstance(Set<Id> recordIds) {
        return (IPayouts) ITBA_Application_UTIL.domain.newInstance(recordIds);
    }

    public PayoutDomain(List<Payout__c> records) {
        super(records);
    }

    public PayoutDomain(List<Payout__c> records, Map<Id, Payout__c> oldPayoutsById) {
        super(records);
        this.oldPayoutsById = oldPayoutsById;
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new PayoutDomain((List<Payout__c>) sObjectList);
        }
    }

    public override void onBeforeInsert() {
        validatePayouts((List<Payout__c>) getRecords());
    }

    public void onBeforeUpdate() {
        this.onBeforeUpdate(getOldRecordsAsSObjects());
    }

    public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
        new PayoutService().validatePayouts(
            getChangedPayouts(existingRecords),
            getOldPayoutsById(existingRecords)
        );
    }

    public void validatePayouts() {
        validatePayouts((List<Payout__c>) getRecords());
    }

    public void validatePayouts(List<Payout__c> payouts) {
        new PayoutService().validatePayouts(payouts);
    }

    private List<Payout__c> getChangedPayouts(Map<Id, SObject> existingRecords) {
        List<Payout__c> changedPayouts = new List<Payout__c>();
        Map<Id, Payout__c> typedExistingRecords = getOldPayoutsById(existingRecords);
        if (typedExistingRecords == null || typedExistingRecords.isEmpty()) {
            return changedPayouts;
        }

        for (Payout__c payout : (List<Payout__c>) getRecords()) {
            Payout__c oldPayout = typedExistingRecords.get(payout.Id);
            if (oldPayout == null) {
                continue;
            }

            if (payout.Transaction__c != oldPayout.Transaction__c ||
                payout.Owner__c != oldPayout.Owner__c ||
                payout.Ownership_Percentage__c != oldPayout.Ownership_Percentage__c ||
                payout.Amount__c != oldPayout.Amount__c ||
                payout.Is_Paid__c != oldPayout.Is_Paid__c ||
                payout.Payment_Transaction__c != oldPayout.Payment_Transaction__c ||
                payout.Remarks__c != oldPayout.Remarks__c) {
                changedPayouts.add(payout);
            }
        }

        return changedPayouts;
    }

    private Map<Id, SObject> getOldRecordsAsSObjects() {
        Map<Id, SObject> typedOldRecords = new Map<Id, SObject>();
        if (this.oldPayoutsById == null) {
            return typedOldRecords;
        }

        for (Id payoutId : this.oldPayoutsById.keySet()) {
            typedOldRecords.put(payoutId, this.oldPayoutsById.get(payoutId));
        }

        return typedOldRecords;
    }

    private Map<Id, Payout__c> getOldPayoutsById(Map<Id, SObject> existingRecords) {
        if (this.oldPayoutsById != null) {
            return this.oldPayoutsById;
        }

        Map<Id, Payout__c> typedExistingRecords = new Map<Id, Payout__c>();
        if (existingRecords == null) {
            return typedExistingRecords;
        }

        for (Id payoutId : existingRecords.keySet()) {
            typedExistingRecords.put(payoutId, (Payout__c) existingRecords.get(payoutId));
        }

        return typedExistingRecords;
    }
}